### ISSUE TITLE
您看一下，跟您测试文件差不多报错了

### ISSUE THREAD

**Issue by york-ly** [ganlvtech/php-enphp-decoder#2]
```plain
F:\php-enphp-decoder>php bin/decode.php tests/assets/admin.php output.php

Warning: gzinflate(): data error in F:\php-enphp-decoder\src\AutoDecoder.php on line 82

Fatal error: Uncaught TypeError: Argument 1 passed to PhpParser\Node\Scalar\String_::__construct() must be of the type string, null given, called in F:\php-enphp-decoder\src\NodeVisitors\GlobalStringNodeVisitor.php on line 32 and defined in F:\php-enphp-decoder\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\String_.php:36
Stack trace:
#0 F:\php-enphp-decoder\src\NodeVisitors\GlobalStringNodeVisitor.php(32): PhpParser\Node\Scalar\String_->__construct(NULL)
#1 F:\php-enphp-decoder\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(153): Ganlv\EnphpDecoder\NodeVisitors\GlobalStringNodeVisitor->leaveNode(Object(PhpParser\Node\Expr\ArrayDimFetch))
#2 F:\php-enphp-decoder\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))
#3 F:\php-enphp-decoder\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\BinaryOp\Concat))
#4 F:\php-enphp-decoder\vendor\nikic\php-parser in F:\php-enphp-decoder\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\String_.php on line 36
```

[admin.txt](https://github.com/ganlvtech/php-enphp-decoder/files/2946372/admin.txt)

**Comment by ganlvtech** [comment]
你提供的文件本身就不能运行。请确认你的文件正确。

如已解决的话，请关闭 Issue。

**Comment by york-ly** [comment]
无法上传php文件，遂改后缀txt上传，请见谅

**Comment by ganlvtech** [comment]
我已经改成了 php，这个文件本身就不能运行，你不解密能直接运行吗？

**Comment by york-ly** [comment]
我也没明文，解密出错的样本就这个

**Comment by ganlvtech** [comment]
不解密能运行吗，不解密都不能运行的话，怎么解密？

**Comment by york-ly** [comment]
可以运行，并且肯定可以解密，只是用你这个解密出错，因为我在云路试过

**Comment by ganlvtech** [comment]
如果你是用 FTP 下载，请改成二进制模式。或者使用 zip 打包重新上传一遍。这个文件我运行不了。
![enphp-decode-error-php-original-file-cannot-run](https://user-images.githubusercontent.com/8651285/54109855-c7985b00-441a-11e9-9ae4-538bd160ec47.jpg)

**Comment by york-ly** [comment]
确实没用二进制下载，估计就是这个问题，怪我怪我，自己电脑没带，等下周回家试试吧
[admin.zip](https://github.com/ganlvtech/php-enphp-decoder/files/2955918/admin.zip)
